pragma solidity ^0.4.23;


contract Logger {

    address public owner;   // address of who creates the contract

    // Land addition event, use this to synchronize with the backend.
    event NewDeploy(address sender);

    // When the contract is deployed by truffle the account that deploys the contract became the owner,
    // in our case it will be the first account generated by ganache-cli (accounts[0]).
    constructor () public{
        owner = msg.sender;
//        emit NewDeploy(msg.sender);
    }

    // Modifier to check if the address of the calling (from field in the transaction obj) is the owner.
    modifier isOwner{
        require(msg.sender == owner, "Not authorized");
        _;
    }

    function emitNewDeployEvent(address _address) public {
        emit NewDeploy(_address);
    }
}